# Convolution연산 구현 (데이터)

In [4]:
import numpy as np

#  5X 5 의 실험용 데이터 생성   
np.random.seed(0)
data = np.random.randint(2, size=(5, 5))
print("Input Data:")
print(data)

# 3x3 필터 생성 (0부터 5까지의 정수)
np.random.seed(0)
filter =  np.random.randint(-1, 1, size=(3, 3))
print("\nConvolution Filter:")
print(filter)


Input Data:
[[0 1 1 0 1]
 [1 1 1 1 1]
 [1 0 0 1 0]
 [0 0 0 0 1]
 [0 1 1 0 0]]

Convolution Filter:
[[-1  0  0]
 [-1  0  0]
 [ 0  0  0]]


# Convolution연산 구현 (함수 및 계산)

In [2]:
# Convoution 함수 정의 (데이터는 arg 인자를 받아오는거까 굳이 self 사용할 필요 없음)
def convolution2d(data, filter):
    filter_size = filter.shape[0]
    data_size = data.shape[0]
    output_size = data_size - filter_size + 1
    output = np.zeros((output_size, output_size))
    #문득 깨달은건데... 정사각형이 아니라 직사각형이면 코딩하기 빡세겠군 나중에 생각해볼 문제
    
    for i in range(output_size):
        for j in range(output_size):
            output[i, j] = np.sum(data[i:i+filter_size, j:j+filter_size] * filter)

    return output

# 합성곱 연산 수행
output = convolution2d(data, filter)

# 결과 출력
print("\nOutput Data after Convolution:")
print(output)


NameError: name 'data' is not defined

저거 구현까지는 얼마 안 걸렸다.
GPT의 힘을 빌리지 않고도 내 순수한 힘만으로도 구현 가능했던 유일한 문제!
(인데 역시 내가 짠 코드랑 GPT가 짠 코드랑 비교해보니까 뭔가 깔끔함이나 가독성 이런게 미묘하게 다르더라...)
(가장 차이 나는건 변수명 센스...)

구현하면서 느낀건데 진짜 간단하게 구현해서 Convoltuon연산이라고 하기도 그럼..
근데 이거 하는데 시간 많이 걸렸다. 저거 구현은 금방 끝났는데,
주제도 모르고 저 과정 애니매이션으로 구현해보겠다고 하고 시간만 날림

자기 능력에 맞게 공부하는게 중요하다. 반성 또 반성.
